### ISSUE TITLE
predict.py有问题

### ISSUE THREAD

**Issue by VectXmy** [aoru45/LFFD-Pytorch#2]
postProcess里是对center form的框做nms，应该先把boxes转换成corner form

**Comment by aoru45** [comment]
非常感谢您，我已经修复重新上传。

**Comment by VectXmy** [comment]
换了loss收敛和改为预测corner form，收敛快很多

**Comment by VectXmy** [comment]
修改assign_prior后dataset.py显示出的目标框不正确，修改前是正确的

**Comment by deep-practice** [comment]
predict.py里面pred_confidence,pred_bbox = net(img)，但模型的返回值有16个，当改成
       pred_score1, pred_bbox1, pred_score2, pred_bbox2, pred_score3, pred_bbox3, pred_score4, pred_bbox4, pred_score5, pred_bbox5, \
        pred_score6, pred_bbox6, pred_score7, pred_bbox7, pred_score8, pred_bbox8 = net(img)
output = post_process(pred_score8,pred_bbox8, width=width, height=height)[0]
又会报下面的错：
  File "D:/projects/python/LFFD-Pytorch/LFFD-Pytorch-master/predict.py", line 52, in pic_test
    output = post_process(pred_score8,pred_bbox8, width=width, height=height)[0]
  File "D:\projects\python\LFFD-Pytorch\LFFD-Pytorch-master\post_processer.py", line 55, in __call__
    boxes = decoded_boxes[mask, :] # x1,y1,x2,y2
IndexError: The shape of the mask [15] at index 0does not match the shape of the indexed tensor [4, 15, 15] at index 0
