### ISSUE TITLE
感受野的计算

### ISSUE THREAD

**Issue by suyue6** [aoru45/LFFD-Pytorch#4]
你好！看到了您的博客：https://www.cnblogs.com/aoru45/p/11456620.html
想请问一下
1、特征间隔，所谓的整个网络的stride这个是具体怎么计算的呀？因为按照RFi=RFi-1+(k-1)s来推的话，第一二层就不符合？喵？
![image](https://user-images.githubusercontent.com/42137529/71391586-bd5ceb80-263f-11ea-93e3-78341a17da33.png)

2、还有比如说c8分支的RF size是55，检测到的连续人脸scale是10-15，请问这个是怎么来的呢？
谢谢~~~

**Comment by aoru45** [comment]
@suyue6
1. 认为第二层感受野就是kernel size，所以公式并不适用于前两层。因此只适用于第三层往后。所谓的整个网络的stride就是你当前层每移动一个像素，对应在原图上的区域移动的步数。全局stride是指，当前层移动一个像素，对应的原图中的区域移动多少步。

重新画一张图举例：
![C25266720979B9BE96A52120C32188DC](https://user-images.githubusercontent.com/34237646/71394303-e2575b80-264b-11ea-855e-b8a63c6928c1.png)

已知第i-1层的感受野是![](http://latex.codecogs.com/gif.latex?RF_{i-1}),也就是说第i-1层上的一个点对应原图的区域的大小是![](http://latex.codecogs.com/gif.latex?RF_{i-1})(如图的绿点对应的绿框)，下一层以conv2x2为例(如图)，那么下一层的感受野就是第0层里四种颜色框的区域的并集(粗略的说)。
那么如何计算这个区域大小呢？假设我们到第i层使用conv k x k，那么不考虑重叠区域大小应该是![](http://latex.codecogs.com/gif.latex?k*RF_{i-1})，然后把重叠部分减掉，就是减去(k-1)(RF_{i-1} - S)，一共有k-1个重叠域，重叠域的宽度为
![](http://latex.codecogs.com/gif.latex?k*RF_{i-1})，然后将上面两部分相减：
k*RF_{i-1} - (k-1)(RF_{i-1} - S)
github公式编辑不太懂，请见谅。

2. ERF的资料在这里：
Understanding the Effective Receptive Field in Deep Convolutional Neural Networks
NIPS 2016

**Comment by suyue6** [comment]
> @suyue6
> 
> 1. 认为第二层感受野就是kernel size，所以公式并不适用于前两层。因此只适用于第三层往后。所谓的整个网络的stride就是你当前层每移动一个像素，对应在原图上的区域移动的步数。全局stride是指，当前层移动一个像素，对应的原图中的区域移动多少步。
> 
> 重新画一张图举例：
> ![C25266720979B9BE96A52120C32188DC](https://user-images.githubusercontent.com/34237646/71394303-e2575b80-264b-11ea-855e-b8a63c6928c1.png)
> 
> 已知第i-1层的感受野是![](https://camo.githubusercontent.com/f784c1557ddf142bef0f8e4f662339400a452e1f/687474703a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f52465f253742692d31253744),也就是说第i-1层上的一个点对应原图的区域的大小是![](https://camo.githubusercontent.com/f784c1557ddf142bef0f8e4f662339400a452e1f/687474703a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f52465f253742692d31253744)(如图的绿点对应的绿框)，下一层以conv2x2为例(如图)，那么下一层的感受野就是第0层里四种颜色框的区域的并集(粗略的说)。
> 那么如何计算这个区域大小呢？假设我们到第i层使用conv k x k，那么不考虑重叠区域大小应该是![](https://camo.githubusercontent.com/320cc9a9c8fa7f6d356bb4fb2abc511bef0bda74/687474703a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f6b2a52465f253742692d31253744)，然后把重叠部分减掉，就是减去(k-1)(RF_{i-1} - S)，一共有k-1个重叠域，重叠域的宽度为
> ![](https://camo.githubusercontent.com/320cc9a9c8fa7f6d356bb4fb2abc511bef0bda74/687474703a2f2f6c617465782e636f6465636f67732e636f6d2f6769662e6c617465783f6b2a52465f253742692d31253744)，然后将上面两部分相减：
> k*RF_{i-1} - (k-1)(RF_{i-1} - S)
> github公式编辑不太懂，请见谅。
> 
> 1. ERF的资料在这里：
>    Understanding the Effective Receptive Field in Deep Convolutional Neural Networks
>    NIPS 2016

get√ 感谢~~~
